

services:
  watermark-app:
    build: .
    container_name: watermark_flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./Audios:/app/Audios
      - ./uploads:/app/uploads
      - ./src/watermark_testing/database:/app/src/watermark_testing/database
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped